Vagrant.configure("2") do |config|

# Ubuntu 64 bit
config.vm.box = "ubuntu/trusty64"

config.vm.provider :virtualbox do |vb|
    # This section can be used for modifying the VM properties
    # Create VM with 1 Gb RAM
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]

    # Change this only if you need desktop for Ubuntu - you will need more memory >= 3Gb
    vb.gui = false

    end
end